### ISSUE TITLE
Session attributes should not automatically be copied over to the response

### ISSUE THREAD

**Issue by OverloadUT** [matt-kruse/alexa-app#12]
Right now, all session attributes that come in as the request are automatically copied by alexa-app in to the response. This is only sometimes going to be desirable, and many times absolutely undesirable behavior. At the very least this should be a feature that can be toggled, and I'd suggest making the default be off. Session attributes will often hold state data, and sending along to the next request would complicate things greatly.

I do think there would be more utility in alexa-app persisting the session attributes in a historical manner, such as in an array of previous requests.

You also have a comment saying something about Alexa not doing this automatically being a bug, but that can't be the case. The response is a JSON object you build yourself; there's no concept of Alexa having any control or insight in to how you do that. There is no response object until you make it!

**Comment by matt-kruse** [comment]
In every other programming environment I'm used to, a "session" attribute persists as long as the session exists, across multiple requests. You don't need to re-set it each time. So on creation of a new session, you may look up user details and persist them in the session, so every subsequent request will have access to it. That's the whole point of a session! Never have I see "session" attributes that automatically disappear after the next request.

That's why I copy them over, so you can set them once and they will get re-sent with each request. IMO, this is a very desirable feature. If you want to clear a session attribute, you can do response.session(key,null).

I guess I could make this optional, but I would still prefer to default it to enabled, because that's what makes sense to me. I'm open to hearing further arguments. :)

**Comment by OverloadUT** [comment]
Oh I see, you thinking of them like cookies. "Here's an attribute, tell me what it is on every subsequent request." I can certainly see that as a way they could have been implemented. I doubt they'll change it to be that way because it would break ASKs already being approved. The ship has sailed! Plus it's trivial to persist any attributes that you want, and that puts more power control in the hands of the developer which is likely the desired outcome.

My main problem with what you're doing is this is a case where you are redefining the default behavior of how Alexa apps work, which I don't think is a module's business and actually makes it more difficult for a developer to switch to using your module. You're basically injecting your belief in how you think the Alexa SDK should have been made in to this implementation.

I think ideally someone should be able to simply move their logic from their own app to one managed by this module without having to change any of the fundamental logic. But with this default behavior, the user would need to rethink how they handled sessionAttributes to ensure that it still works.

Another reason it's undesirably is that someone reading the source code of an app built on alexa-app will likely not know about this redefined behavior and when trying to understand how the app works, will make (reasonable) false conclusions. If the app had a call in there saying "persist all session attributes" then it would be more semantically understandable.

**Comment by matt-kruse** [comment]
I see your point, but I do disagree. Every web programmer I know will expect "session" attributes to actually persist for the whole session. That's how sessions work! So, yes, this module is a little opinionated in that way, but I think it will actually make life much easier for most developers. By default, it will behave in the way they naturally expect.

I've just added a new option for the next (2.1) release that I'm working on:

app.persistentSession=false;

This will turn off the default behavior.

**Comment by OverloadUT** [comment]
Oh I hadn't seen this yet. Perfect!
